import type { Metadata } from "next";
import "./globals.css";
import "../styles/theme.scss";
import Provider from "./provider";

export const metadata: Metadata = {
  title: "GHC Audit App",
  description: "Generated by GHC Audit app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en" suppressHydrationWarning >
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
